name: authd-msentraid
summary: MS EntraID Broker for authd
description: |
  Broker that enables OIDC authentication with MS EntraID group management for authd.
version: "0.1"
grade: stable
base: core24
confinement: strict
license: GPL-3.0

apps:
  authd-msentraid:
    command: bin/authd-msentraid
    daemon: simple
    slots:
      - dbus-authd
    plugs:
      - network
      - config-file
    restart-condition: always

slots:
  dbus-authd:
    interface: dbus
    bus: system
    name: com.ubuntu.authd.MSEntraID

plugs:
  config-file:
    interface: system-files
    read:
      - /etc/authd/brokers.d/msentraid

parts:
  broker:
    source: .
    source-type: local
    plugin: go
    go-buildtags: [withmsentraid]
    build-snaps:
      - go
    override-build: |
      go mod download all
      go build -tags=withmsentraid -o ${GOBIN}/authd-msentraid ./cmd/authd-oidc
