name: msentraid-broker
summary: MS EntraID Broker for authd
description: |
  Broker that enables OIDC authentication with MS EntraID group management for authd.
version: "0.1"
grade: stable
base: core24
confinement: strict
license: GPL-3.0+

apps:
  msentraid-broker:
    command: bin/msentraid-broker
    daemon: simple
    slots:
      - dbus-oidc
    plugs:
      - network
      - config-files
    restart-condition: always

slots:
  dbus-oidc:
    interface: dbus
    bus: system
    name: com.ubuntu.authd.MSEntraIDBroker

plugs:
  config-files:
    interface: system-files
    read:
      - /etc/authd/brokers.d/msentraid-broker

parts:
  msentraid-broker:
    source: .
    source-type: local
    plugin: go
    go-buildtags: [withmsentraid]
    build-snaps:
      - go
    override-build: |
      go mod download all
      go build -tags=withmsentraid -o ${GOBIN}/msentraid-broker ./cmd/oidc-broker
